apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  # this will be a digital ocean LB to distribute traffic across all the pods
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80 # for the outside domain: http:/xxx.xx.xx.xxx:80, default port,
      targetPort: 80 # port the deployment/pod is running on
  selector:
    app: nginx-deployment
