apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment
    spec:
      containers:
        - name: iac-python
          image: codingforentrepreneurs/iac-python:latest
          env:
            - name: PORT
              value: "8181"
          ports:
            - containerPort: 8181
---
apiVersion: v1
kind: Service
metadata:
  name: iac-python-service
spec:
  # this will be a digital ocean LB to distribute traffic across all the pods
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80 # for the outside domain: http:/xxx.xx.xx.xxx:80, default port,
      targetPort: 8181 # port the deployment/pod is running on
  selector:
    app: iac-python-deployment
